FROM node

RUN mkdir /wesworld
WORKDIR /wesworld

COPY front_end/package.json /wesworld/package.json
COPY front_end/src /wesworld/src
COPY front_end/public /wesworld/public

RUN npm install

# CMD npm start

RUN apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt-get install nodejs -y
RUN npm install webpack -g
RUN npm install
COPY webpack.config.js /wesworld
CMD webpack --watch --watch-poll
